// react/src/_deprecated/InputSingleLine.js
import React from 'react';

const InputSingleLine = ({ label, value, onChange, onBlur, error, warning }) => {
    const inputClass = `shadow appearance-none border ${
        error ? 'border-red-500' : (warning ? 'border-yellow-500' : 'border-gray-300')
    } text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500`;

    const labelClass = "block text-gray-700 text-sm font-bold mb-2";
    const errorClass = "text-red-500 text-xs italic";
    const warningClass = "text-yellow-500 text-xs italic";

    return (
        <div>
            {label && <label className={labelClass}>{label}</label>}
            <input 
                type="text" 
                value={value} 
                onChange={onChange} 
                onBlur={onBlur} 
                className={inputClass}
            />
            {error && <p className={errorClass}>{error}</p>}
            {warning && !error && <p className={warningClass}>{warning}</p>}
        </div>
    );
};

export default InputSingleLine;

// angular/projects/ng-twixt/src/lib/input-single-line/input-single-line.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-input-single-line',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input-single-line.component.html',
  styleUrls: ['./input-single-line.component.css']
})
export class InputSingleLineComponent {
  @Input() label: string = '';
  @Input() value: string = '';
  @Input() error: string = '';
  @Input() warning: string = '';

  @Output() valueChange = new EventEmitter<string>();
  @Output() blur = new EventEmitter<void>();

  onInputChange(event: Event) {
    const input = event.target as HTMLInputElement;
    this.valueChange.emit(input.value);
  }

  onInputBlur() {
    this.blur.emit();
  }

  getInputClass(): string {
    return `shadow appearance-none border ${
      this.error ? 'border-red-500' : (this.warning ? 'border-yellow-500' : 'border-gray-300')
    } text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5`;
    // Add dark mode classes if needed
  }
}

<div class="mb-4">
    <ng-container *ngIf="label">
      <label class="block text-gray-700 text-sm font-bold mb-2">{{ label }}</label>
    </ng-container>
    <input type="text" [value]="value" (input)="onInputChange($event)" (blur)="onInputBlur()" [class]="getInputClass()" />
    <p *ngIf="error" class="text-red-500 text-xs italic">{{ error }}</p>
    <p *ngIf="warning && !error" class="text-yellow-500 text-xs italic">{{ warning }}</p>
  </div>
